# 进入MySQL命令行
SHOW VARIABLES LIKE 'local_infile';

LOAD DATA LOCAL INFILE 'E:\DATAbasets\cookie_cats.csv' INTO TABLE cookie_cats
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

